// showcases/vue-showcase/src/components/textarea/Textarea.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/textarea.json";
import { DBTextarea } from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="Textarea" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBTextarea>{{ exampleName }}</DBTextarea>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/textarea/textarea.component.ts
import { Component } from '@angular/core';

import defaultComponentVariants from '../../../../../shared/textarea.json';

@Component({
	selector: 'app-textarea',
	templateUrl: './textarea.component.html'
})
export class TextareaComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="Textarea"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-textarea>{{ exampleName }}</db-textarea>
	</ng-template>
</app-default-component>
